#!/bin/sh

DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

for in_file in debian/*.acc.in; do
    out_file=${in_file%.in}
    sed 's/@@DEB_HOST_MULTIARCH@@/'"${DEB_HOST_MULTIARCH}"'/' \
        "${in_file}" > "${out_file}"
done

DH_VERBOSE=1

# Disable acc test till abi-compliance-checker gets fixed
# #820070
dh_acc || true
ret=$?
if [ 0 -ne $ret ]; then
    cp -r logs "${ADT_ARTIFACTS}"/acc.logs
fi
exit $ret
