#!/bin/sh

# kcoreaddons puts the build path into a test, we need to rebuild
# everything to make sure the path is the temporary one used for
# the autopkgtest. NB: cmake hates relocation, so we'd have to
# mangle CMakeCache.txt to get away with a as-needed-rebuild :/
debian/rules clean 2>&1
dpkg-source --before-build .
debian/rules build 2>&1

dh_auto_test
