#!/bin/sh

if [ -z "$HOME" ] || [ ! -d "$HOME" ]; then
    [ -e debian/tests.home ] || mkdir debian/tests.home
    export HOME="$(pwd)/debian/tests.home"
    trap "rm -rf debian/tests.home" EXIT
fi
mkdir -p "$HOME"/.config || true
debian/rules build 2>&1

dh_auto_test
